
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RealEstate.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Property
{

    public int Id { get; set; }

    public string PropertyName { get; set; }

    public string Description { get; set; }

    public Nullable<int> Rooms { get; set; }

    public Nullable<double> Size { get; set; }

    public Nullable<int> Floors { get; set; }

    public Nullable<int> LocationId { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public Nullable<int> AgentId { get; set; }



    public virtual Category Category { get; set; }

    public virtual Location Location { get; set; }

    public virtual User User { get; set; }

}

}
